name: Picodrive CI
on: [push, pull_request]
jobs:
  build-libretro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: make
      run: LDFLAGS=-Wl,--no-undefined make -j$(getconf _NPROCESSORS_ONLN) -f Makefile.libretro
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Win32
        path: /*.dll