name: Picodrive CI
on: [push, pull_request]

jobs:
  build-win-dll:
    runs-on: ubuntu-latest
    container: ghcr.io/irixxxx/toolchain-win32
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set Platform to Win
      run: echo "platform=win" >> $GITHUB_ENV
    - name: build
      run: |
        git config --global --add safe.directory $PWD
        ver=$(cut -d'"' -f2 platform/common/version.h)-$(git rev-parse --short HEAD)
        make -j$(getconf _NPROCESSORS_ONLN) -f Makefile.libretro TARGET=PicoDrive_libretro.dll
    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WinDLL
        path: PicoDrive_libretro.dll